# Generated by Django 6.0 on 2026-01-02 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã đơn vị')),
                ('name', models.CharField(max_length=50, verbose_name='Tên đơn vị')),
                ('temp_reset', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên đối tác')),
                ('partner_type', models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('SUPPLIER', 'Nhà cung cấp'), ('BOTH', 'Vừa là Khách vừa là NCC')], default='CUSTOMER', max_length=10, verbose_name='Loại đối tác')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_partne_name_d26c5a_idx'), models.Index(fields=['partner_type'], name='core_partne_partner_4c9cf7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã sản phẩm/SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('product_type', models.CharField(choices=[('RAW', 'Nguyên liệu gỗ thô'), ('FINISHED', 'Thành phẩm'), ('BYPRODUCT', 'Phụ phẩm')], max_length=10, verbose_name='Loại sản phẩm')),
                ('min_stock_threshold', models.PositiveIntegerField(default=50, verbose_name='Ngưỡng tồn kho tối thiểu')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả kích thước/quy cách')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá tham khảo')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit', verbose_name='Đơn vị tính')),
            ],
            options={
                'indexes': [models.Index(fields=['sku'], name='core_produc_sku_a1eae6_idx'), models.Index(fields=['product_type'], name='core_produc_product_3906a7_idx')],
            },
        ),
    ]
