# Generated by Django 6.0 on 2026-01-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='temp_reset',
        ),
    ]
