# Generated by Django 6.0 on 2026-01-02 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã lệnh SX')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('PLANNED', 'Đã lên kế hoạch'), ('IN_PROGRESS', 'Đang thực hiện'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Hủy bỏ')], default='PLANNED', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú SX')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số lượng thu được')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian thực hiện')),
                ('raw_qty_used', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số lượng gỗ tiêu thụ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
