# Generated by Django 6.0 on 2026-01-02 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_unit_temp_reset'),
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='sale_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.saleorder', verbose_name='Sản xuất cho Đơn hàng'),
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Thành phẩm/Phụ phẩm'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='production.productionorder', verbose_name='Thuộc lệnh SX'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='raw_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_runs', to='inventory.batch', verbose_name='Lô gỗ nguyên liệu (Input)'),
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='production.productionrun'),
        ),
    ]
