# Generated by Django 6.0 on 2026-03-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='total_input',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='total_output',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='wastage_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='wastage_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
