# Generated by Django 6.0 on 2026-03-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionorder_total_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã lệnh SX'),
        ),
    ]
