# Generated by Django 6.0 on 2026-01-02 03:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_unit_temp_reset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True, verbose_name='Mã lô')),
                ('import_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Sản phẩm/Gỗ')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.partner', verbose_name='Nhà cung cấp')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IMPORT', 'Nhập kho'), ('EXPORT', 'Xuất kho'), ('ADJUST', 'Kiểm kê/Điều chỉnh')], max_length=10, verbose_name='Loại giao dịch')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số lượng')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian giao dịch')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Diễn giải')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.batch', verbose_name='Lô hàng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_code'], name='inventory_b_batch_c_e2e545_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['import_date'], name='inventory_b_import__b3161d_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product'], name='inventory_b_product_fec8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['supplier'], name='inventory_b_supplie_9d0d88_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['batch', 'transaction_type'], name='inventory_i_batch_i_4e003c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['date'], name='inventory_i_date_c147aa_idx'),
        ),
    ]
