# Generated by Django 6.0 on 2026-01-02 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_unit_temp_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đặt')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Ngày giao dự kiến')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('CONFIRMED', 'Đã chốt đơn'), ('PRODUCTION', 'Đang sản xuất'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('customer', models.ForeignKey(limit_choices_to={'partner_type': 'CUSTOMER'}, on_delete=django.db.models.deletion.PROTECT, to='core.partner', verbose_name='Khách hàng')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Sản phẩm')),
            ],
        ),
    ]
